import { Employee } from './employee.model';

export const EMPLOYEES: Employee[]=[
    {     id:  1,
        email: 'abc@test.com',
        firstName: 'Jack',
        lastName: 'Cyro',
        imagePath: "../../assets/images/Default-profile.jpg",
        gender: "male",
        address: "Test Address",
        mobile: 9999999999 },    {     id:  2,
            email: 'abc@test.com',
            firstName: 'Jack',
            lastName: 'Cyro',
            imagePath: "../../assets/images/Default-profile.jpg",
            gender: "male",
            address: "Test Address",
            mobile: 9999999999 },
            {     id:  3,
                email: 'abc@test.com',
                firstName: 'Jack',
                lastName: 'Cyro',
                imagePath: "../../assets/images/Default-profile.jpg",
                gender: "male",
                address: "Test Address",
                mobile: 9999999999 },
                {     id:  4,
                    email: 'abc@test.com',
                    firstName: 'Jack',
                    lastName: 'Cyro',
                    imagePath: "../../assets/images/Default-profile.jpg",
                    gender: "male",
                    address: "Test Address",
                    mobile: 9999999999 },
                    {     id:  5,
                        email: 'abc@test.com',
                        firstName: 'Jack',
                        lastName: 'Cyro',
                        imagePath: "../../assets/images/Default-profile.jpg",
                        gender: "male",
                        address: "Test Address",
                        mobile: 9999999999 },
                        {     id:  6,
                            email: 'abc@test.com',
                            firstName: 'Jack',
                            lastName: 'Cyro',
                            imagePath: "../../assets/images/Default-profile.jpg",
                            gender: "male",
                            address: "Test Address",
                            mobile: 9999999999 },
                            {     id:  7,
                                email: 'abc@test.com',
                                firstName: 'Jack',
                                lastName: 'Cyro',
                                imagePath: "../../assets/images/Default-profile.jpg",
                                gender: "male",
                                address: "Test Address",
                                mobile: 9999999999 },
                                {     id:  8,
                                    email: 'abc@test.com',
                                    firstName: 'Jack',
                                    lastName: 'Cyro',
                                    imagePath: "../../assets/images/Default-profile.jpg",
                                    gender: "male",
                                    address: "Test Address",
                                    mobile: 9999999999 }
]